### ISSUE TITLE
Firebase client SDK 보안 문제

### ISSUE THREAD

**Issue by hyun-Bell** [hayeon9826/findaoverflow#15]
다음 링크( https://github.com/nextauthjs/next-auth/issues/5049 )에 따르면 현재 next-auth에서 사용하는 FirebaseAdapter는 브라우저에서 동작하는 Firebase Client SDK를 사용하기 때문에 Firebase의 Security rules를 마음대로 변경 가능하도록 열어야 하는 보안 문제가 있습니다.

또 jwt를 사용하여 인증을 하도록 되어있는데 현재 Sessions라는 별도의 데이터베이스를 만들어서 jwt 인증과 세션 인증을 불필요하게 병행하고 있습니다. 인증 방식을 정리할 필요가 있어보입니다.

**Comment by hyun-Bell** [comment]
[현재]
<img width="951" alt="image" src="https://user-images.githubusercontent.com/74768098/196003804-2cc1a8e5-9d10-49b0-a1ba-14b35026a6a3.png">
대략 현재 보안 문제를 정의해봤습니다. 
일반적으로 자바스크립트에서 파이어베이스에 액세스하기 위해 Firebase Client SDK가 제공됩니다. (우리 코드에서 config/firebase)
아무리 env 값으로 관련 키들을 숨겼지만 브라우저에서 파이어베이스로 직접 요청하기 때문에 당연히 노출됩니다.
즉, 다른 사용자가 우리 DB에 접근해서 데이터를 가져가거나 쓸 수 있습니다.

[수정 후]
<img width="746" alt="image" src="https://user-images.githubusercontent.com/74768098/196004090-ffe995eb-904c-4ccf-a8bc-9c14eb68f032.png">

변경사항
- 브라우저에서 직접 파이어베이스로 호출하는 일을 없애기
- Firebase Client SDK로 설정되어 있는 것도 없애고 Firebase Admin SDK를 이용해 Next.js에서 요청 (모든 접근은 Next.js API routes를 통하기)
- Admin SDK에서 권한 클레임을 설정하여 Firebase Storage에서 제공하는 Security rules를 설정하여 보안 강화

**Comment by hayeon9826** [comment]
기존 config/firebase.ts 설정을 Admin firebase sdk 로 변경해서 JWT 설정을 따로 하면 되는걸까요? Firebase Admin jwt는 저도 안해봐서 리서치 후 적용해볼게요!
