### ISSUE TITLE
Tui Editor React 18 린트 에러 문제

### ISSUE THREAD

**Issue by hayeon9826** [hayeon9826/findaoverflow#16]
- 현재 린트를 돌리면 Tui Editor과 React 버전 의존성 문제 때문에 에러가 뜸

- Tui Editor에 문의를 해보았지만, 현재로서는 리액트 18에 맞는 버전이 없다고 함. 가장 최신 버전이 리액트 17 의존
- 링크: https://github.com/nhn/tui.editor/issues/2790
- 문의 결과 지금 바쁘니까 고칠때까지 기다리거나, 직접 고쳐서 쓰라는 답변 받음 ㅎㅎ..

해결방안:
1. Tui Editor 걷어내고 다른 에디터 사용한다
2. 직접 Tui Editor 라이브러리 고쳐서 배포한다
3. ESLint에서 일시적으로 해당 에러 무시하도록 설정한다

@manOfBackend 현재 위와같은 문제인데 어떻게 해결하는게 좋을까요??
언제 고쳐질지 모르니까 무기한 기다리는 것은 어려울 것 같고, 만약 대체한다면 웹팀에서 사용한다는 [Lexical Editor](https://lexical.dev/)로 변경해도 될 것 같아요. 아니면 오픈소스 기여하는 김에 wrapper 변경해서 사용해보는 것도 괜찮을 것 같은..?

**Comment by hyun-Bell** [comment]
lexical editor로 가시죠! react18은 써야할 것 같아요.

**Comment by hayeon9826** [comment]
> lexical editor로 가시죠! react18은 써야할 것 같아요.

~~넵 주말내에 완성해서 린트 문제 해결해보는것으로..!~~

도큐가 별로 없어서 시간이 꽤 걸릴 것 같네요
